Repository uwblueprint/dancefest-web, pull requests merged in 2019-01, with the labels that each got.

#27 Fixes instant Empty State flash
  package.json
  src/components/adjudications/AdjudicationsSection.jsx
  src/components/events/EventForm.jsx
  src/components/events/EventTableRow.jsx
  src/components/events/EventsSection.jsx
  src/components/images/Adjudications_empty.jpg
  src/components/images/Adjudications_empty.png
  src/components/images/Events_empty.jpg
  src/components/images/Events_empty.png
  src/components/images/Performances_empty.jpg
  src/components/images/Performances_empty.png
  src/components/interface/EmptyStates.jsx
  src/components/interface/Loading.jsx
  src/components/interface/Section.jsx
  src/components/performances/PerformancesSection.jsx
  src/components/styles.js
Labels: review

#28 Firebase Auth
  package-lock.json
  src/components/App.jsx
  src/components/SignIn.jsx
  src/components/interface/Button.jsx
  src/constants/routes.js
  src/firebase/firebase.js
Labels: enhancement, review

#29 Fixes Section Header Error
  src/components/events/EventsSection.jsx
  src/components/interface/Section.jsx
  src/components/interface/SectionHeader.jsx
  src/components/performances/PerformancesSection.jsx
Labels: review

#15 Integrate Dancefest Admin with Firestore
  package-lock.json
  package.json
  src/components/App.jsx
  src/components/SignIn.jsx
  src/components/adjudications/AdjudicationDialog.jsx
  src/components/adjudications/AdjudicationForm.jsx
  src/components/adjudications/AdjudicationTableRow.jsx
  src/components/adjudications/AdjudicationTestData.jsx
  src/components/adjudications/AdjudicationsSection.jsx
  src/components/events/EventDialog.jsx
  src/components/events/EventForm.jsx
  src/components/events/EventTableRow.jsx
  src/components/events/EventsSection.jsx
  src/components/events/TestData.jsx
  src/components/images/Adjudications_empty.jpg
  src/components/images/Adjudications_empty.png
  src/components/images/Events_empty.jpg
  src/components/images/Events_empty.png
  src/components/images/Performances_empty.jpg
  src/components/images/Performances_empty.png
  src/components/interface/AudioPlay.jsx
  src/components/interface/Button.jsx
  src/components/interface/CheckBox.jsx
  src/components/interface/EmptyStates.jsx
  src/components/interface/Loading.jsx
  src/components/interface/Section.jsx
  src/components/interface/SectionHeader.jsx
  src/components/interface/TableFilters.jsx
  src/components/interface/TableHeader.jsx
  src/components/interface/dialog/DFDialog.jsx
  src/components/interface/dialog/DialogHeader.jsx
  src/components/interface/dialog/DialogInput.jsx
  src/components/interface/dialog/DialogReadOnly.jsx
  src/components/interface/dialog/DialogSelect.jsx
  src/components/interface/dialog/Score.jsx
  src/components/interface/editing/AlertDialog.jsx
  src/components/interface/editing/EditDropdown.jsx
  src/components/performances/PerformanceDialog.jsx
  src/components/performances/PerformanceForm.jsx
  src/components/performances/PerformanceTableRow.jsx
  src/components/performances/PerformanceTestData.jsx
  src/components/performances/PerformancesSection.jsx
  src/components/settings/SettingData.jsx
  src/components/settings/SettingsSection.jsx
  src/components/styles.js
  src/constants.js
  src/constants/routes.js
  src/firebase/database.js
  src/firebase/firebase.js
  src/firebase/utils/addData.js
  src/firebase/utils/deleteData.js
  src/firebase/utils/updateData.js
  src/firebase/utils/updateSettings.js
Labels: doing

#32 Adds ability to keep state for filter and handles filter object
  src/components/adjudications/AdjudicationForm.jsx
  src/components/interface/CheckBox.jsx
  src/components/interface/Section.jsx
  src/components/interface/TableFilters.jsx
  src/components/interface/filter/EnhancedMenu.jsx
  src/components/interface/filter/FilterItem.jsx
  src/components/interface/filter/FilterMenu.jsx
  src/components/interface/filter/SubMenu.jsx
  src/components/interface/filter/index.jsx
  src/components/performances/PerformancesSection.jsx
  src/components/styles.js
Labels: review

#31 Dropdown for settings / logout, back button & event deletion
  src/components/events/EventDialog.jsx
  src/components/interface/Header.jsx
  src/components/interface/SectionHeader.jsx
  src/components/interface/settings/SettingsDropdown.jsx
  src/components/settings/SettingsSection.jsx
  src/components/styles.js
Labels: review
